version: '2'
services:
  zookeeper:
    build: ./zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: kafka-single-node
#      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      HOSTNAME_COMMAND: "hostname -I | awk '{ print $1 }'" ### current ip addres
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
